server:
  port: 8443

spring:
  application:
    name: price-control
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    移动云测试环境
    url: jdbc:mysql://{{MYSQL_IP}}:{{MYSQL_PORT}}/tourism?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: {{MYSQL_USER}}
    password: {{MYSQL_PWD}}
    druid:
      test-while-idle: false
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB

# mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath:mapper/*.xml
  #type-aliases-package: com.lun.entity    # 所有Entity别名类所在包
  # 全局配置
  global-config:
    db-config:
      # 逻辑删除全局字段 (默认无 设置会自动扫描实体字段)
      logic-delete-field: delFlag
      # 逻辑删除全局值（默认 1、表示已删除）
      logic-delete-value: 1
      # 逻辑未删除全局值（默认 0、表示未删除）
      logic-not-delete-value: 0

