server:
  port: 8080

spring:
  application:
    name: component-mybatis
  datasource:

    #driver-class-name: com.alibaba.druid.proxy.DruidDriver
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    username: graps
    password: 123456
    url: jdbc:mysql://172.16.40.102:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    druid:
      test-while-idle: false

logging:
  level:
    com.meng.dao : debug

mybatis:
  mapper-locations: classpath:mapper/*.xml



